spring.application.name=trackflowapp

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
